const startingBoard = [
  {
    id: 0,
    place: "A8",
    hasPiece: true,
    selected: false,
    hasMoved: false,
    color: "black",
    column: 1,
    row: 8,
    piece: "rook",
    img: "",
  },
  {
    id: 1,
    place: "B8",
    hasPiece: true,
    selected: false,
    hasMoved: false,
    color: "black",
    column: 2,
    row: 8,
    piece: "knight",
    img: "",
  },
  {
    id: 2,
    place: "C8",
    hasPiece: true,
    selected: false,
    hasMoved: false,
    color: "black",
    column: 3,
    row: 8,
    piece: "bishop",
    img: "",
  },
  {
    id: 3,
    place: "D8",
    hasPiece: true,
    selected: false,
    hasMoved: false,
    color: "black",
    column: 4,
    row: 8,
    piece: "queen",
    img: "",
  },
  {
    id: 4,
    place: "E8",
    hasPiece: true,
    selected: false,
    hasMoved: false,
    color: "black",
    column: 5,
    row: 8,
    piece: "king",
    img: "",
  },
  {
    id: 5,
    place: "F8",
    hasPiece: true,
    selected: false,
    hasMoved: false,
    color: "black",
    column: 6,
    row: 8,
    piece: "bishop",
    img: "",
  },
  {
    id: 6,
    place: "G8",
    hasPiece: true,
    selected: false,
    hasMoved: false,
    color: "black",
    column: 7,
    row: 8,
    piece: "knight",
    img: "",
  },
  {
    id: 7,
    place: "H8",
    hasPiece: true,
    selected: false,
    hasMoved: false,
    color: "black",
    column: 8,
    row: 8,
    piece: "rook",
    img: "",
  },
  {
    id: 8,
    place: "A7",
    hasPiece: true,
    selected: false,
    hasMoved: false,
    color: "black",
    column: 1,
    row: 7,
    piece: "pawn",
    img: "",
  },
  {
    id: 9,
    place: "B7",
    hasPiece: true,
    selected: false,
    hasMoved: false,
    color: "black",
    column: 2,
    row: 7,
    piece: "pawn",
    img: "",
  },
  {
    id: 10,
    place: "C7",
    hasPiece: true,
    selected: false,
    hasMoved: false,
    color: "black",
    column: 3,
    row: 7,
    piece: "pawn",
    img: "",
  },
  {
    id: 11,
    place: "D7",
    hasPiece: true,
    selected: false,
    hasMoved: false,
    color: "black",
    column: 4,
    row: 7,
    piece: "pawn",
    img: "",
  },
  {
    id: 12,
    place: "E7",
    hasPiece: true,
    selected: false,
    hasMoved: false,
    color: "black",
    column: 5,
    row: 7,
    piece: "pawn",
    img: "",
  },
  {
    id: 13,
    place: "F7",
    hasPiece: true,
    selected: false,
    hasMoved: false,
    color: "black",
    column: 6,
    row: 7,
    piece: "pawn",
    img: "",
  },
  {
    id: 14,
    place: "G7",
    hasPiece: true,
    selected: false,
    hasMoved: false,
    color: "black",
    column: 7,
    row: 7,
    piece: "pawn",
    img: "",
  },
  {
    id: 15,
    place: "H7",
    hasPiece: true,
    selected: false,
    hasMoved: false,
    color: "black",
    column: 8,
    row: 7,
    piece: "pawn",
    img: "",
  },
  {
    id: 16,
    place: "A6",
    hasPiece: false,
    selected: false,
    hasMoved: false,
    color: "",
    column: 1,
    row: 6,
    piece: "",
    img: "",
  },
  {
    id: 17,
    place: "B6",
    hasPiece: false,
    selected: false,
    hasMoved: false,
    color: "",
    column: 2,
    row: 6,
    piece: "",
    img: "",
  },
  {
    id: 18,
    place: "C6",
    hasPiece: false,
    selected: false,
    hasMoved: false,
    color: "",
    column: 3,
    row: 6,
    piece: "",
    img: "",
  },
  {
    id: 19,
    place: "D6",
    hasPiece: false,
    selected: false,
    hasMoved: false,
    color: "",
    column: 4,
    row: 6,
    piece: "",
    img: "",
  },
  {
    id: 20,
    place: "E6",
    hasPiece: false,
    selected: false,
    hasMoved: false,
    color: "",
    column: 5,
    row: 6,
    piece: "",
    img: "",
  },
  {
    id: 21,
    place: "F6",
    hasPiece: false,
    selected: false,
    hasMoved: false,
    color: "",
    column: 6,
    row: 6,
    piece: "pawn",
    img: "",
  },
  {
    id: 22,
    place: "G6",
    hasPiece: true,
    selected: false,
    hasMoved: false,
    color: "",
    column: 7,
    row: 6,
    piece: "",
    img: "",
  },
  {
    id: 23,
    place: "H6",
    hasPiece: false,
    selected: false,
    hasMoved: false,
    color: "",
    column: 8,
    row: 6,
    piece: "",
    img: "",
  },
  {
    id: 24,
    place: "A5",
    hasPiece: false,
    selected: false,
    hasMoved: false,
    color: "",
    column: 1,
    row: 5,
    piece: "",
    img: "",
  },
  {
    id: 25,
    place: "B5",
    hasPiece: false,
    selected: false,
    hasMoved: false,
    color: "",
    column: 2,
    row: 5,
    piece: "",
    img: "",
  },
  {
    id: 26,
    place: "C5",
    hasPiece: false,
    selected: false,
    hasMoved: false,
    color: "",
    column: 3,
    row: 5,
    piece: "",
    img: "",
  },
  {
    id: 27,
    place: "D5",
    hasPiece: false,
    selected: false,
    hasMoved: false,
    color: "",
    column: 4,
    row: 5,
    piece: "",
    img: "",
  },
  {
    id: 28,
    place: "E5",
    hasPiece: false,
    selected: false,
    hasMoved: false,
    color: "",
    column: 5,
    row: 5,
    piece: "",
    img: "",
  },
  {
    id: 29,
    place: "F5",
    hasPiece: false,
    selected: false,
    hasMoved: false,
    color: "",
    column: 6,
    row: 5,
    piece: "",
    img: "",
  },
  {
    id: 30,
    place: "G5",
    hasPiece: false,
    selected: false,
    hasMoved: false,
    color: "",
    column: 7,
    row: 5,
    piece: "",
    img: "",
  },
  {
    id: 31,
    place: "H5",
    hasPiece: false,
    selected: false,
    hasMoved: false,
    color: "",
    column: 8,
    row: 5,
    piece: "",
    img: "",
  },
  {
    id: 32,
    place: "A4",
    hasPiece: false,
    selected: false,
    hasMoved: false,
    color: "",
    column: 1,
    row: 4,
    piece: "",
    img: "",
  },
  {
    id: 33,
    place: "B4",
    hasPiece: false,
    selected: false,
    hasMoved: false,
    color: "",
    column: 2,
    row: 4,
    piece: "",
    img: "",
  },
  {
    id: 34,
    place: "C4",
    hasPiece: false,
    selected: false,
    hasMoved: false,
    color: "",
    column: 3,
    row: 4,
    piece: "",
    img: "",
  },
  {
    id: 35,
    place: "D4",
    hasPiece: false,
    selected: false,
    hasMoved: false,
    color: "",
    column: 4,
    row: 4,
    piece: "",
    img: "",
  },
  {
    id: 36,
    place: "E4",
    hasPiece: false,
    selected: false,
    hasMoved: false,
    color: "",
    column: 5,
    row: 4,
    piece: "",
    img: "",
  },
  {
    id: 37,
    place: "F4",
    hasPiece: false,
    selected: false,
    hasMoved: false,
    color: "",
    column: 6,
    row: 4,
    piece: "",
    img: "",
  },
  {
    id: 38,
    place: "G4",
    hasPiece: false,
    selected: false,
    hasMoved: false,
    color: "",
    column: 7,
    row: 4,
    piece: "",
    img: "",
  },
  {
    id: 39,
    place: "H4",
    hasPiece: false,
    selected: false,
    hasMoved: false,
    color: "",
    column: 8,
    row: 4,
    piece: "",
    img: "",
  },
  {
    id: 40,
    place: "A3",
    hasPiece: false,
    selected: false,
    hasMoved: false,
    color: "",
    column: 1,
    row: 3,
    piece: "",
    img: "",
  },
  {
    id: 41,
    place: "B3",
    hasPiece: false,
    selected: false,
    hasMoved: false,
    color: "",
    column: 2,
    row: 3,
    piece: "",
    img: "",
  },
  {
    id: 42,
    place: "C3",
    hasPiece: false,
    selected: false,
    hasMoved: false,
    color: "",
    column: 3,
    row: 3,
    piece: "",
    img: "",
  },
  {
    id: 43,
    place: "D3",
    hasPiece: false,
    selected: false,
    hasMoved: false,
    color: "",
    column: 4,
    row: 3,
    piece: "",
    img: "",
  },
  {
    id: 44,
    place: "E3",
    hasPiece: false,
    selected: false,
    hasMoved: false,
    color: "",
    column: 5,
    row: 3,
    piece: "",
    img: "",
  },
  {
    id: 45,
    place: "F3",
    hasPiece: false,
    selected: false,
    hasMoved: false,
    color: "",
    column: 6,
    row: 3,
    piece: "",
    img: "",
  },
  {
    id: 46,
    place: "G3",
    hasPiece: false,
    selected: false,
    hasMoved: false,
    color: "",
    column: 7,
    row: 3,
    piece: "",
    img: "",
  },
  {
    id: 47,
    place: "H3",
    hasPiece: false,
    selected: false,
    hasMoved: false,
    color: "",
    column: 8,
    row: 3,
    piece: "",
    img: "",
  },
  {
    id: 48,
    place: "A2",
    hasPiece: true,
    selected: false,
    hasMoved: false,
    color: "white",
    column: 1,
    row: 2,
    piece: "pawn",
    img: "",
  },
  {
    id: 49,
    place: "B2",
    hasPiece: true,
    selected: false,
    hasMoved: false,
    color: "white",
    column: 2,
    row: 2,
    piece: "pawn",
    img: "",
  },
  {
    id: 50,
    place: "C2",
    hasPiece: true,
    selected: false,
    hasMoved: false,
    color: "white",
    column: 3,
    row: 2,
    piece: "pawn",
    img: "",
  },
  {
    id: 51,
    place: "D2",
    hasPiece: true,
    selected: false,
    hasMoved: false,
    color: "white",
    column: 4,
    row: 2,
    piece: "pawn",
    img: "",
  },
  {
    id: 52,
    place: "E2",
    hasPiece: true,
    selected: false,
    hasMoved: false,
    color: "white",
    column: 5,
    row: 2,
    piece: "pawn",
    img: "",
  },
  {
    id: 53,
    place: "F2",
    hasPiece: true,
    selected: false,
    hasMoved: false,
    color: "white",
    column: 6,
    row: 2,
    piece: "pawn",
    img: "",
  },
  {
    id: 54,
    place: "G2",
    hasPiece: true,
    selected: false,
    hasMoved: false,
    color: "white",
    column: 7,
    row: 2,
    piece: "pawn",
    img: "",
  },
  {
    id: 55,
    place: "H2",
    hasPiece: true,
    selected: false,
    hasMoved: false,
    color: "white",
    column: 8,
    row: 2,
    piece: "pawn",
    img: "",
  },
  {
    id: 56,
    place: "A1",
    hasPiece: true,
    selected: false,
    hasMoved: false,
    color: "white",
    column: 1,
    row: 1,
    piece: "rook",
    img: "",
  },
  {
    id: 57,
    place: "B1",
    hasPiece: true,
    selected: false,
    hasMoved: false,
    color: "white",
    column: 2,
    row: 1,
    piece: "knight",
    img: "",
  },
  {
    id: 58,
    place: "C1",
    hasPiece: true,
    selected: false,
    hasMoved: false,
    color: "white",
    column: 3,
    row: 1,
    piece: "bishop",
    img: "",
  },
  {
    id: 59,
    place: "D1",
    hasPiece: true,
    selected: false,
    hasMoved: false,
    color: "white",
    column: 4,
    row: 1,
    piece: "queen",
    img: "",
  },
  {
    id: 60,
    place: "E1",
    hasPiece: true,
    selected: false,
    hasMoved: false,
    color: "white",
    column: 5,
    row: 1,
    piece: "king",
    img: "",
  },
  {
    id: 61,
    place: "F1",
    hasPiece: true,
    selected: false,
    hasMoved: false,
    color: "white",
    column: 6,
    row: 1,
    piece: "bishop",
    img: "",
  },
  {
    id: 62,
    place: "G1",
    hasPiece: true,
    selected: false,
    hasMoved: false,
    color: "white",
    column: 7,
    row: 1,
    piece: "knight",
    img: "",
  },
  {
    id: 63,
    place: "H1",
    hasPiece: true,
    selected: false,
    hasMoved: false,
    color: "white",
    column: 8,
    row: 1,
    piece: "rook",
    img: "",
  },
];

export default startingBoard;
